### ISSUE TITLE
infer more then one cond control

### ISSUE THREAD

**Issue by zdxpan** [salesforce/UniControl#10]
how to infer with more the 1 condition?

**Comment by abrarmajeedi** [comment]
Same question

**Comment by canqin001** [comment]
For multi-condition control, please add their MoE's features with the weighted average and concatenate their task prompts.

**Comment by gallenszl** [comment]
> For multi-condition control, please add their MoE's features with the weighted average and concatenate their task prompts.

Hello, could you please provide a sample code for such multi-condition control? We have tried to implement it by ourselves. But it seems the generated result is not very good.
