### ISSUE TITLE
defference between cldm_v15_unicontrol_v11.yaml and cldm_v15_unicontrol.yaml

### ISSUE THREAD

**Issue by amandaluof** [salesforce/UniControl#13]
Thanks for your great work! I notice that there are two yamls and two ckpts. For the yamls, it seems that they corresponds to cldm_unicontrol and cldm_unicontrol_v11. The main differences are: (1)whether use zero_conv for self.input_hint_block_zeroconv_0 and self.input_hint_block_zeroconv_1 (2)whether use self.input_hint_block_zeroconv_0[1] and self.input_hint_block_zeroconv_1[1] for (guided_hint) guided_hint (3) whether task_id_layernet and task_id_hypernet. cldm_unicontrol_v11 uses the zero_convs and   self.input_hint_block_zeroconv_x[1], and open the network structures about task_id.

I have two questions: (1) does that mean unicontrol.ckpt correspond to  cldm_v15_unicontrol.yaml and unicontrol_v1.1.ckpt correspond to  cldm_v15_unicontrol_v1.1.yaml ?  (2) I am trying adapting the deblur task to another datastet, which yaml and ckpt shoule I use? (3) what's the special purpose for the above design? (4) Using the released ckpt for  debluring, I got following results which seem to collapse, is it reasonable?

input image:
![image](https://github.com/salesforce/UniControl/assets/44992004/6dd4e251-ef5d-4d38-a84f-40cec4a526b1)

prompt:
""

output:
![image](https://github.com/salesforce/UniControl/assets/44992004/a6c79eed-17bb-4e09-b439-1078aac77d92)

**Comment by canqin001** [comment]
My mistake. unicontrol_v1.1.ckpt  is not aligned with cldm_v15_unicontrol_v1.1.yaml. **Please use cldm_v15_unicontrol.yaml all the time (even for unicontrol_v1.1.ckpt)!!!**

**Comment by canqin001** [comment]
BTW, our HF space is available (https://huggingface.co/spaces/Robert001/UniControl-Demo). Please feel free to play with it!

**Comment by amandaluof** [comment]
> My mistake. unicontrol_v1.1.ckpt is not aligned with cldm_v15_unicontrol_v1.1.yaml. **Please use cldm_v15_unicontrol.yaml all the time (even for unicontrol_v1.1.ckpt)!!!**

Thank you!
