### ISSUE TITLE
This work sounds similar Uni-Controlnet, any connection?

### ISSUE THREAD

**Issue by TruthSearcher** [salesforce/UniControl#21]
This work sounds similar to to Uni-Controlnet, any connection?
https://github.com/ShihaoZhaoZSH/Uni-ControlNet

**Comment by canqin001** [comment]
Thank you for your question. Uni-ControlNet is also a very interesting project. The first version UniControl paper is uploaded to arXiv on 05/18/23 (https://arxiv.org/abs/2305.11147v1) that is one-week earlier than Uni-ControlNet released on 05/25/23. They are different projects with different mythologies. It could be a coincidence for the similar titles.
