### ISSUE TITLE
How much disk storage space is needed for the decompressed data?

### ISSUE THREAD

**Issue by liming-ai** [salesforce/UniControl#24]
I noticed that all the compressed files take up 2.2T of disk space. How much disk storage space is needed for the decompressed data?

**Comment by canqin001** [comment]
It should be the similar space (~2.2T).

**Comment by liming-ai** [comment]
Just for future reference~
```
1.2T    ./conditions
6.7G    ./json_files
1.3T    ./images
2.5T    .
```
