### ISSUE TITLE
Will the training data MultiGen-20M release?

### ISSUE THREAD

**Issue by trouble-maker007** [salesforce/UniControl#5]
Thank you for open-sourcing such a great work. I would like to know if the MultiGen-20M dataset will be released to the public in the future

**Comment by yihaocs** [comment]
Yes. As mentioned in the paper, we will release the **MultiGen-20M** dataset to contribute to the community very soon.  Please make a star of our repo and keep an eye on it.

**Comment by shugerdou** [comment]
The data is released. Thanks for your interest in our work.

**Comment by trouble-maker007** [comment]
@shugerdou Would you like to introduce how to generate the training data?

**Comment by shugerdou** [comment]
@trouble-maker007  we follow https://github.com/lllyasviel/ControlNet/tree/main/annotator to extract conditions. The raw data is from https://huggingface.co/datasets/ChristophSchuhmann/improved_aesthetics_6plus
