### ISSUE TITLE
Error when running the demo

### ISSUE THREAD

**Issue by dydxdt** [salesforce/UniControl#7]
Hi, thanks for your grear job!
When I run "python gradio_all_tasks.py", it can launch successfully, but if I upload an image and click 'run', the error occurs like this :
![image](https://github.com/salesforce/UniControl/assets/46140371/7d93811e-c33b-481b-a9e1-559857a19d65)
I wonder whether this  is the CUDA version problem. I just installed CUDAtoolkit 11.3 as in the environment.yaml.
Thanks!!

**Comment by canqin001** [comment]
I have never met this error before. Can you test your env on the inference code? Please let me know if it still has errors.
`CUDA_VISIBLE_DEVICES=0 python inference_demo.py --ckpt ./ckpts/unicontrol.ckpt --task canny`

**Comment by dydxdt** [comment]
Thanks for you reply!
I just find that if I don't install xformers, it can work fine. If I use pip to install xformers, it seems to uninstall pytorch1.12.1 and install pytorch1.13. So I don't install xformers now. Can you provide your xformers version and pytorch version? And is  xformers necessary and helpful to give better results?

**Comment by canqin001** [comment]
I see. I do not use xformers as well. I am not sure if xformers will give better results.
